<a href="https://colab.research.google.com/github/tiwaripari/ML/blob/main/moodsclassificationipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [69]:
df = pd.read_csv("/content/drive/MyDrive/data_moods.csv")

In [70]:
df

,name,album,artist,id,release_date,popularity,length,danceability,acousticness,energy,instrumentalness,liveness,valence,loudness,speechiness,tempo,key,time_signature,mood
0,1999,1999,Prince,2H7PHVdQ3mXqEHXcvclTB0,1982-10-27,68,379266,0.866,0.13700,0.7300,0.000000,0.0843,0.6250,-8.201,0.0767,118.523,5,4,Happy
1,23,23,Blonde Redhead,4HIwL9ii9CcXpTOTzMq0MP,2007-04-16,43,318800,0.381,0.01890,0.8320,0.196000,0.1530,0.1660,-5.069,0.0492,120.255,8,4,Sad
2,9 Crimes,9,Damien Rice,5GZEeowhvSieFDiR8fQ2im,2006-11-06,60,217946,0.346,0.91300,0.1390,0.000077,0.0934,0.1160,-15.326,0.0321,136.168,0,4,Sad
3,99 Luftballons,99 Luftballons,Nena,6HA97v4wEGQ5TUClRM0XLc,1984-08-21,2,233000,0.466,0.08900,0.4380,0.000006,0.1130,0.5870,-12.858,0.0608,193.100,4,4,Happy
4,A Boy Brushed Red Living In Black And White,They're Only Chasing Safety,Underoath,47IWLfIKOKhFnz1FUEUIkE,2004-01-01,60,268000,0.419,0.00171,0.9320,0.000000,0.1370,0.4450,-3.604,0.1060,169.881,1,4,Energetic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,windcatcher,windcatcher,Leo Nocta,59VApBbrS2IADQk4ml5mdo,2020-06-19,36,123066,0.402,0.96100,0.2360,0.919000,0.0921,0.1460,-20.615,0.0603,129.736,0,3,Calm
682,yellow is the color of her eyes,yellow is the color of her eyes,Soccer Mommy,4D3nttJPU6L0M2epr7sId6,2019-11-19,5,435080,0.452,0.75700,0.5150,0.120000,0.1400,0.1910,-7.351,0.0255,80.537,11,4,Sad
683,you broke me first,you broke me first,Tate McRae,45bE4HXI0AwGZXfZtMp8JR,2020-04-17,87,169265,0.642,0.78600,0.3740,0.000000,0.0906,0.0799,-9.386,0.0545,124.099,4,4,Sad
684,you were good to me,brent,Jeremy Zucker,4CxFN5zON70B3VOPBYbd6P,2019-05-03,76,219146,0.561,0.91300,0.0848,0.000026,0.1120,0.2060,-15.099,0.0404,102.128,2,4,Sad
685,æfre,æfre,praam,2irbT1BSYaIEF44PlyKaoM,2020-07-17,41,186331,0.377,0.99400,0.0156,0.881000,0.0991,0.0804,-28.435,0.0397,140.179,0,4,Calm

In [71]:
df.isnull().sum()

name                0
album               0
artist              0
id                  0
release_date        0
popularity          0
length              0
danceability        0
acousticness        0
energy              0
instrumentalness    0
liveness            0
valence             0
loudness            0
speechiness         0
tempo               0
key                 0
time_signature      0
mood                0
dtype: int64

In [72]:
df.mood.value_counts()

Sad          197
Calm         195
Energetic    154
Happy        140
Name: mood, dtype: int64

In [25]:
# col_drop = ["name", "album", "artist", "release_date", "popularity", "length"]
# df = df.drop(columns = col_drop)

In [73]:
df

,name,album,artist,id,release_date,popularity,length,danceability,acousticness,energy,instrumentalness,liveness,valence,loudness,speechiness,tempo,key,time_signature,mood
0,1999,1999,Prince,2H7PHVdQ3mXqEHXcvclTB0,1982-10-27,68,379266,0.866,0.13700,0.7300,0.000000,0.0843,0.6250,-8.201,0.0767,118.523,5,4,Happy
1,23,23,Blonde Redhead,4HIwL9ii9CcXpTOTzMq0MP,2007-04-16,43,318800,0.381,0.01890,0.8320,0.196000,0.1530,0.1660,-5.069,0.0492,120.255,8,4,Sad
2,9 Crimes,9,Damien Rice,5GZEeowhvSieFDiR8fQ2im,2006-11-06,60,217946,0.346,0.91300,0.1390,0.000077,0.0934,0.1160,-15.326,0.0321,136.168,0,4,Sad
3,99 Luftballons,99 Luftballons,Nena,6HA97v4wEGQ5TUClRM0XLc,1984-08-21,2,233000,0.466,0.08900,0.4380,0.000006,0.1130,0.5870,-12.858,0.0608,193.100,4,4,Happy
4,A Boy Brushed Red Living In Black And White,They're Only Chasing Safety,Underoath,47IWLfIKOKhFnz1FUEUIkE,2004-01-01,60,268000,0.419,0.00171,0.9320,0.000000,0.1370,0.4450,-3.604,0.1060,169.881,1,4,Energetic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,windcatcher,windcatcher,Leo Nocta,59VApBbrS2IADQk4ml5mdo,2020-06-19,36,123066,0.402,0.96100,0.2360,0.919000,0.0921,0.1460,-20.615,0.0603,129.736,0,3,Calm
682,yellow is the color of her eyes,yellow is the color of her eyes,Soccer Mommy,4D3nttJPU6L0M2epr7sId6,2019-11-19,5,435080,0.452,0.75700,0.5150,0.120000,0.1400,0.1910,-7.351,0.0255,80.537,11,4,Sad
683,you broke me first,you broke me first,Tate McRae,45bE4HXI0AwGZXfZtMp8JR,2020-04-17,87,169265,0.642,0.78600,0.3740,0.000000,0.0906,0.0799,-9.386,0.0545,124.099,4,4,Sad
684,you were good to me,brent,Jeremy Zucker,4CxFN5zON70B3VOPBYbd6P,2019-05-03,76,219146,0.561,0.91300,0.0848,0.000026,0.1120,0.2060,-15.099,0.0404,102.128,2,4,Sad
685,æfre,æfre,praam,2irbT1BSYaIEF44PlyKaoM,2020-07-17,41,186331,0.377,0.99400,0.0156,0.881000,0.0991,0.0804,-28.435,0.0397,140.179,0,4,Calm

In [74]:
#Creating Test and Train data
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
#View top 10 rows
df.head(10)

,name,album,artist,id,release_date,popularity,length,danceability,acousticness,energy,instrumentalness,liveness,valence,loudness,speechiness,tempo,key,time_signature,mood,is_train
0,1999,1999,Prince,2H7PHVdQ3mXqEHXcvclTB0,1982-10-27,68,379266,0.866,0.137000,0.7300,0.000000,0.0843,0.625,-8.201,0.0767,118.523,5,4,Happy,False
1,23,23,Blonde Redhead,4HIwL9ii9CcXpTOTzMq0MP,2007-04-16,43,318800,0.381,0.018900,0.8320,0.196000,0.1530,0.166,-5.069,0.0492,120.255,8,4,Sad,True
2,9 Crimes,9,Damien Rice,5GZEeowhvSieFDiR8fQ2im,2006-11-06,60,217946,0.346,0.913000,0.1390,0.000077,0.0934,0.116,-15.326,0.0321,136.168,0,4,Sad,True
3,99 Luftballons,99 Luftballons,Nena,6HA97v4wEGQ5TUClRM0XLc,1984-08-21,2,233000,0.466,0.089000,0.4380,0.000006,0.1130,0.587,-12.858,0.0608,193.100,4,4,Happy,False
4,A Boy Brushed Red Living In Black And White,They're Only Chasing Safety,Underoath,47IWLfIKOKhFnz1FUEUIkE,2004-01-01,60,268000,0.419,0.001710,0.9320,0.000000,0.1370,0.445,-3.604,0.1060,169.881,1,4,Energetic,True
5,A Burden to Bear,A Burden to Bear,Emmanuelle Rimbaud,67DOFCrkcQaLp5yhzF8Y8N,2020-07-31,27,129410,0.394,0.995000,0.0475,0.955000,0.1050,0.172,-26.432,0.0720,71.241,6,5,Calm,True
6,A La Plage,A La Plage,Ron Adelaar,79NmiFAgcXUIVDGfCWDdWF,2020-08-07,29,141888,0.504,0.994000,0.0584,0.956000,0.1150,0.553,-20.461,0.0516,134.209,5,4,Calm,True
7,A Little Less Conversation - JXL Radio Edit Remix,Elvis 75 - Good Rockin' Tonight,Elvis Presley,4l2hnfUx0esSbITQa7iJt0,2009-12-28,1,211173,0.586,0.000155,0.9350,0.277000,0.1590,0.580,-9.386,0.0482,114.997,4,4,Happy,True
8,A Place for My Head,Hybrid Theory (Bonus Edition),Linkin Park,5rAxhWcgFng3s570sGO2F8,2000-10-24,68,184640,0.603,0.014400,0.9080,0.000000,0.6710,0.457,-5.254,0.1840,133.063,11,4,Energetic,True
9,ATTACK,A Beautiful Lie + 30 Seconds To Mars,Thirty Seconds To Mars,6QxTWEvzcJljVZaeTzuHF1,2007-05-15,0,189200,0.331,0.003440,0.8760,0.000835,0.7320,0.299,-1.894,0.0603,175.009,5,4,Energetic,True

In [75]:
df

,name,album,artist,id,release_date,popularity,length,danceability,acousticness,energy,instrumentalness,liveness,valence,loudness,speechiness,tempo,key,time_signature,mood,is_train
0,1999,1999,Prince,2H7PHVdQ3mXqEHXcvclTB0,1982-10-27,68,379266,0.866,0.13700,0.7300,0.000000,0.0843,0.6250,-8.201,0.0767,118.523,5,4,Happy,False
1,23,23,Blonde Redhead,4HIwL9ii9CcXpTOTzMq0MP,2007-04-16,43,318800,0.381,0.01890,0.8320,0.196000,0.1530,0.1660,-5.069,0.0492,120.255,8,4,Sad,True
2,9 Crimes,9,Damien Rice,5GZEeowhvSieFDiR8fQ2im,2006-11-06,60,217946,0.346,0.91300,0.1390,0.000077,0.0934,0.1160,-15.326,0.0321,136.168,0,4,Sad,True
3,99 Luftballons,99 Luftballons,Nena,6HA97v4wEGQ5TUClRM0XLc,1984-08-21,2,233000,0.466,0.08900,0.4380,0.000006,0.1130,0.5870,-12.858,0.0608,193.100,4,4,Happy,False
4,A Boy Brushed Red Living In Black And White,They're Only Chasing Safety,Underoath,47IWLfIKOKhFnz1FUEUIkE,2004-01-01,60,268000,0.419,0.00171,0.9320,0.000000,0.1370,0.4450,-3.604,0.1060,169.881,1,4,Energetic,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,windcatcher,windcatcher,Leo Nocta,59VApBbrS2IADQk4ml5mdo,2020-06-19,36,123066,0.402,0.96100,0.2360,0.919000,0.0921,0.1460,-20.615,0.0603,129.736,0,3,Calm,True
682,yellow is the color of her eyes,yellow is the color of her eyes,Soccer Mommy,4D3nttJPU6L0M2epr7sId6,2019-11-19,5,435080,0.452,0.75700,0.5150,0.120000,0.1400,0.1910,-7.351,0.0255,80.537,11,4,Sad,True
683,you broke me first,you broke me first,Tate McRae,45bE4HXI0AwGZXfZtMp8JR,2020-04-17,87,169265,0.642,0.78600,0.3740,0.000000,0.0906,0.0799,-9.386,0.0545,124.099,4,4,Sad,False
684,you were good to me,brent,Jeremy Zucker,4CxFN5zON70B3VOPBYbd6P,2019-05-03,76,219146,0.561,0.91300,0.0848,0.000026,0.1120,0.2060,-15.099,0.0404,102.128,2,4,Sad,False
685,æfre,æfre,praam,2irbT1BSYaIEF44PlyKaoM,2020-07-17,41,186331,0.377,0.99400,0.0156,0.881000,0.0991,0.0804,-28.435,0.0397,140.179,0,4,Calm,True

In [76]:
no_features = len(df.columns)
no_features

20

In [77]:
#Create dataframes with train and test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

#show the number of rows in test and train dataframe
print("training data ", len(train))
print("testing data ", len(test))

training data  526
testing data  160

In [78]:
#Converting each mood name into digits
y = pd.factorize(train['mood'])[0]
#viewing target

target_names = pd.factorize(train['mood'])[1]
y

array([0, 0, 1, 2, 2, 3, 1, 1, 1, 2, 1, 3, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       2, 2, 0, 0, 1, 1, 3, 1, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 2, 1, 0, 1,
       2, 0, 3, 0, 2, 1, 0, 0, 1, 1, 1, 0, 2, 0, 3, 2, 3, 2, 1, 3, 0, 3,
       2, 2, 3, 1, 2, 3, 2, 2, 1, 0, 1, 2, 3, 1, 0, 0, 3, 1, 2, 3, 1, 3,
       3, 0, 2, 2, 2, 0, 3, 1, 0, 1, 0, 0, 2, 2, 2, 0, 3, 2, 0, 0, 1, 0,
       3, 3, 3, 0, 3, 1, 0, 2, 3, 1, 1, 0, 3, 0, 2, 1, 0, 2, 2, 2, 3, 1,
       0, 1, 0, 0, 1, 1, 3, 1, 2, 0, 2, 2, 0, 0, 2, 1, 2, 2, 0, 1, 2, 2,
       3, 3, 1, 2, 2, 1, 3, 1, 0, 2, 1, 1, 0, 2, 2, 2, 2, 3, 1, 1, 1, 3,
       3, 0, 3, 0, 1, 3, 1, 1, 3, 3, 0, 3, 3, 0, 0, 2, 1, 3, 3, 0, 1, 0,
       0, 2, 2, 2, 2, 1, 2, 2, 2, 0, 1, 0, 0, 2, 0, 3, 0, 0, 2, 2, 0, 1,
       0, 0, 3, 3, 1, 2, 0, 3, 2, 3, 0, 3, 1, 2, 0, 1, 1, 3, 1, 2, 0, 3,
       1, 2, 3, 3, 1, 0, 3, 0, 2, 0, 2, 0, 0, 3, 2, 2, 1, 2, 0, 3, 2, 2,
       3, 2, 2, 2, 0, 3, 2, 2, 2, 3, 3, 1, 0, 1, 3, 1, 0, 3, 3, 0, 2, 0,
       1, 1, 0, 0, 0, 2, 2, 3, 1, 0, 2, 2, 0, 1, 1, 1, 0, 0, 2, 2, 1, 1,
       1, 0, 0, 0, 2, 1, 1, 2, 0, 1, 0, 2, 2, 3, 2, 2, 0, 1, 1, 2, 1, 2,
       2, 2, 2, 1, 1, 3, 2, 2, 0, 1, 2, 0, 1, 1, 2, 2, 1, 0, 0, 3, 0, 3,
       1, 0, 0, 2, 1, 1, 0, 1, 2, 1, 3, 3, 0, 2, 1, 3, 0, 0, 2, 2, 3, 0,
       0, 0, 3, 2, 2, 0, 3, 0, 3, 0, 0, 1, 3, 3, 1, 2, 2, 3, 1, 0, 3, 2,
       3, 3, 1, 0, 2, 2, 0, 3, 0, 0, 1, 3, 3, 2, 3, 2, 1, 3, 0, 0, 0, 2,
       0, 2, 2, 2, 2, 0, 0, 1, 0, 3, 1, 0, 0, 2, 3, 2, 0, 2, 1, 1, 0, 0,
       2, 0, 3, 2, 2, 0, 0, 2, 1, 2, 0, 2, 3, 2, 1, 2, 3, 0, 3, 2, 1, 2,
       0, 2, 2, 1, 0, 3, 3, 1, 3, 0, 1, 3, 3, 1, 2, 0, 0, 3, 0, 2, 2, 0,
       2, 0, 2, 1, 1, 1, 2, 3, 1, 2, 2, 0, 0, 0, 1, 2, 3, 2, 0, 3, 0, 0,
       3, 3, 0, 1, 3, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2])

In [79]:
#Converting each mood name into digits for test data
x = pd.factorize(test['mood'])[0]
#viewing target
x

array([0, 0, 1, 2, 0, 3, 0, 1, 1, 0, 0, 3, 2, 0, 2, 2, 1, 3, 0, 2, 3, 2,
       1, 3, 1, 1, 2, 2, 1, 0, 3, 3, 2, 1, 2, 3, 2, 1, 0, 2, 1, 0, 0, 3,
       1, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0, 2, 2, 2, 1, 3, 3, 3, 0, 1, 3, 2,
       3, 3, 0, 1, 1, 1, 3, 3, 0, 3, 0, 2, 2, 1, 1, 1, 3, 2, 2, 1, 2, 0,
       1, 3, 0, 1, 1, 2, 0, 2, 1, 1, 2, 3, 1, 3, 1, 0, 2, 1, 2, 0, 1, 0,
       3, 3, 2, 0, 1, 3, 3, 1, 2, 0, 2, 0, 3, 3, 0, 1, 2, 0, 2, 3, 3, 1,
       3, 3, 1, 0, 0, 3, 3, 2, 0, 0, 1, 1, 1, 3, 2, 0, 1, 1, 1, 1, 0, 2,
       1, 1, 3, 3, 3, 3])

In [80]:
target_names

Index(['Sad', 'Energetic', 'Calm', 'Happy'], dtype='object')

In [83]:
features = df.columns[5:18]
features

Index(['popularity', 'length', 'danceability', 'acousticness', 'energy',
       'instrumentalness', 'liveness', 'valence', 'loudness', 'speechiness',
       'tempo', 'key', 'time_signature'],
      dtype='object')

In [84]:
models = []
models.append(('Random Forest Classifier',RandomForestClassifier()))
models.append(('Gradient Boosting Classifier',GradientBoostingClassifier()))
models.append(('XGB Classifier', XGBClassifier()))
models.append(('Decision Tree Classifier', DecisionTreeClassifier()))
models.append(('LGBM Classifier', LGBMClassifier()))
models.append(('Support Vector Classifier', SVC()))
models.append(('KNN Classifier', KNeighborsClassifier()))

In [85]:
for name, model in models:
    model.fit(train[features], y)

    predictions = model.predict(test[features])
    accuracy = accuracy_score(predictions, x)

    print('Accuracy for {} : {:3.3f}\nClassification Report for {} : \n{}'.format(name, accuracy_score(predictions, x) * 100, name, classification_report(predictions, x, target_names=target_names)))

Accuracy for Random Forest Classifier : 6.250
Classification Report for Random Forest Classifier :
              precision    recall  f1-score   support

         Sad       0.23      0.19      0.21        47
   Energetic       0.00      0.00      0.00        41
        Calm       0.00      0.00      0.00        44
       Happy       0.03      0.04      0.03        28

    accuracy                           0.06       160
   macro avg       0.06      0.06      0.06       160
weighted avg       0.07      0.06      0.07       160

Accuracy for Gradient Boosting Classifier : 5.000
Classification Report for Gradient Boosting Classifier :
              precision    recall  f1-score   support

         Sad       0.12      0.12      0.12        42
   Energetic       0.00      0.00      0.00        39
        Calm       0.00      0.00      0.00        43
       Happy       0.07      0.08      0.08        36

    accuracy                           0.05       160
   macro avg       0.05      0.05      0.05       160
weighted avg       0.05      0.05      0.05       160

Accuracy for XGB Classifier : 5.000
Classification Report for XGB Classifier :
              precision    recall  f1-score   support

         Sad       0.12      0.12      0.12        42
   Energetic       0.00      0.00      0.00        38
        Calm       0.00      0.00      0.00        43
       Happy       0.07      0.08      0.08        37

    accuracy                           0.05       160
   macro avg       0.05      0.05      0.05       160
weighted avg       0.05      0.05      0.05       160

Accuracy for Decision Tree Classifier : 10.625
Classification Report for Decision Tree Classifier :
              precision    recall  f1-score   support

         Sad       0.23      0.20      0.21        46
   Energetic       0.00      0.00      0.00        32
        Calm       0.00      0.00      0.00        43
       Happy       0.20      0.21      0.20        39

    accuracy                           0.11       160
   macro avg       0.11      0.10      0.10       160
weighted avg       0.11      0.11      0.11       160

Accuracy for LGBM Classifier : 5.625
Classification Report for LGBM Classifier :
              precision    recall  f1-score   support

         Sad       0.17      0.15      0.16        48
   Energetic       0.00      0.00      0.00        38
        Calm       0.00      0.00      0.00        40
       Happy       0.05      0.06      0.05        34

    accuracy                           0.06       160
   macro avg       0.06      0.05      0.05       160
weighted avg       0.06      0.06      0.06       160

Accuracy for Support Vector Classifier : 26.875
Classification Report for Support Vector Classifier :
              precision    recall  f1-score   support

         Sad       0.62      0.29      0.39        87
   Energetic       0.00      0.00      0.00         0
        Calm       0.50      0.25      0.33        73
       Happy       0.00      0.00      0.00         0

    accuracy                           0.27       160
   macro avg       0.28      0.13      0.18       160
weighted avg       0.57      0.27      0.36       160

Accuracy for KNN Classifier : 25.000
Classification Report for KNN Classifier :
              precision    recall  f1-score   support

         Sad       0.45      0.23      0.30        80
   Energetic       0.23      0.33      0.27        30
        Calm       0.22      0.19      0.21        42
       Happy       0.10      0.50      0.17         8

    accuracy                           0.25       160
   macro avg       0.25      0.31      0.24       160
weighted avg       0.33      0.25      0.26       160

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [45]:
#viewing predicted probablities of first 10 observation
clf.predict_proba(test[features])[:10]

array([[0.33, 0.14, 0.53, 0.  ],
       [0.48, 0.01, 0.51, 0.  ],
       [0.3 , 0.01, 0.69, 0.  ],
       [0.24, 0.08, 0.64, 0.04],
       [0.38, 0.54, 0.01, 0.07],
       [0.04, 0.  , 0.96, 0.  ],
       [0.19, 0.6 , 0.12, 0.09],
       [0.05, 0.01, 0.94, 0.  ],
       [0.06, 0.  , 0.94, 0.  ],
       [0.83, 0.05, 0.12, 0.  ]])

In [46]:
#mapping names of moods for each music for each predicted mood
preds  = target_names[clf.predict(test[features])]

#View the predicted moods for firat five observations
preds[10:20]

Index(['Sad', 'Energetic', 'Energetic', 'Calm', 'Sad', 'Sad', 'Happy', 'Sad',
       'Calm', 'Energetic'],
      dtype='object')

In [47]:
#Creating confusion matrix
#crosstab takes two sets of data and forms chart out of it
pd.crosstab(test['mood'], preds, rownames=['Actual mood'], colnames=['Predicted Species'])

Predicted Species  Calm  Energetic  Happy  Sad
Actual mood
Calm                 45          0      0    0
Energetic             0         31      4    0
Happy                 0          8     24    8
Sad                   1          3      3   37

In [48]:
accuracy = accuracy_score(x, predictions)

In [49]:
accuracy*100

34.146341463414636